### ISSUE TITLE
Not working on Windows and Linux (tested on Windows sub-system)

### ISSUE THREAD

**Issue by johannnovak** [jtara1/horriblesubs_batch_downloader#10]
Hello,

I've tried to use your python script to batch download from HorribleSubs, however it crashes on startup on Windows and Linux.
Here is the call stack on Linux (it is roughly the same on Windows) : 

 Traceback (most recent call last):
  File "/usr/local/bin/hsbd", line 11, in <module>
    sys.exit(main_cli_wrapped())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/horriblesubs_batch_downloader/__main__.py", line 45, in main_cli_wrapped
    main(search_word, cache_dir, download)
  File "/usr/local/lib/python3.5/dist-packages/horriblesubs_batch_downloader/__main__.py", line 22, in main
    shows_file = scraper.save_shows_to_file(cache_dir)
  File "/usr/local/lib/python3.5/dist-packages/horriblesubs_batch_downloader/shows_scraper.py", line 62, in save_shows_to_file
    with open(file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/tmp/tmp/shows.json'

Environment : 
* Windows 10 with Python 3.6.5
* Linux sub-system (so Ubuntu) with Python 3.5.2

If you need any other information, just ask.

Johann

**Comment by HariC137** [comment]
I am also facing a similar issue 
in windows 10 system
   hsbd naruto
Traceback (most recent call last):
  File "C:\Users\hari1\AppData\Local\Programs\Python\Python37\Scripts\hsbd-script.py", line 11, in <module>
    load_entry_point('horriblesubs-batch-downloader==0.2.9', 'console_scripts', 'hsbd')()
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\horriblesubs_batch_downloader\__main__.py", line 45, in main_cli_wrapped
    main(search_word, cache_dir, download)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\horriblesubs_batch_downloader\__main__.py", line 22, in main
    shows_file = scraper.save_shows_to_file(cache_dir)
  File "c:\users\hari1\appdata\local\programs\python\python37\lib\site-packages\horriblesubs_batch_downloader\shows_scraper.py", line 62, in save_shows_to_file
    with open(file, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hari1\\tmp/shows.json'

**Comment by Jacquest1** [comment]
Solved: Create a "shows.json" file in Users\tmp.

**Comment by jtara1** [comment]
fixed in 0.3.0 available via github or pypi 

`pip install -U horriblesubs-batch-downloader` via your shell / cmd

tested on Win10 with python 3.6.0
