### ISSUE TITLE
Support for alpha-numerical episode numbers

### ISSUE THREAD

**Issue by johannnovak** [jtara1/horriblesubs_batch_downloader#13]
Hello,

HSBD works great for all standard animes. However I stumbled on "Re:Zero" (https://horriblesubs.info/shows/re-zero-kara-hajimeru-isekai-seikatsu/) and this anime contains episodes with letters inside 01A and 01B). And of course, it cannot be cast as an int.

Here is the call stack :
<pre>
Traceback (most recent call last):
  File "D:\Programs\Python3\Scripts\hsbd-script.py", line 11, in <module>
    load_entry_point('horriblesubs-batch-downloader==0.3.0', 'console_scripts', 'hsbd')()
  File "D:\Programs\Python3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\Python3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\Programs\Python3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\Python3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\Programs\Python3\lib\site-packages\horriblesubs_batch_downloader\__main__.py", line 45, in main_cli_wrapped
    main(search_word, cache_dir, download)
  File "D:\Programs\Python3\lib\site-packages\horriblesubs_batch_downloader\__main__.py", line 29, in main
    ep_scraper = EpisodesScraper(show_url=show_url, debug=True)
  File "D:\Programs\Python3\lib\site-packages\horriblesubs_batch_downloader\episodes_scraper.py", line 98, in __init__
    key=lambda episode_info:
  File "D:\Programs\Python3\lib\site-packages\horriblesubs_batch_downloader\episodes_scraper.py", line 101, in <lambda>
    else int(episode_info['episode_number'])
ValueError: invalid literal for int() with base 10: '01B'
</pre>

Keep on the good work !
Johann

**Comment by AlexMusabelliu** [comment]
in the pull requests, i put an updated ver. with this feature

**Comment by jtara1** [comment]
should be implemented in #15 thanks to @AlexMusabelliu
